#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to CapRover, Open Source PaaS for developers!


Follow the guide here to finish the setup https://caprover.com/docs/get-started.html#step-3-install-caprover-cli

Or you can access the dashboard from http://$myip:3000

The default password is captain42




Please make sure to read the documentation https://CapRover.com


********************************************************************************

EOF

